name: Publishing benchmark results

on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: test
        run: |
          pwd
          ls -artl .
          ls -artl ..
          ls -artl ~

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: pySDC Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: latest-benchmark/output.json
          auto-push: true
          benchmark-data-dir-path: .
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    runs-on: ubuntu-latest

    env:
      YML: 'env.yml'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ env.YML }}

      - name: Prepare data
        run: |
          python -m coverage combine latest-coverage/coverage_*.dat
          python -m coverage xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'