name: Publishing benchmark results

on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: test
        run: |
          pwd
          ls -artl .
          ls -artl ..
          ls -artl ~

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: pySDC Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          auto-push: true
          benchmark-data-dir-path: .
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
